spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_opc?useUnicode=true&characterEncoding=UTF-8

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

mybatis:
  type-aliases-package: com.mall.provider.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.mall.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

security:
  oauth2:
    client:
      clientId: mall-client-opc
      clientSecret: mallClientSecret
      access-token-uri: http://mall-gateway:7979/uac/oauth/token
      user-authorization-uri: http://mall-gateway:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://mall-gateway:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://mall-provider-uac:8000/oauth/token_key

mall:
  enableSqlLogInterceptor: false
  token:
    interceptor:
      enable: true
  zk:
    zkAddressList: mall-provider-zk:2181
  qiniu:
    key:
      accessKey: yourQiniuAccessKey
      secretKey: yourQiniuSecretKey
    oss:
      privateHost:
      publicHost:
      fileMaxSize: 104857600
  oauth2:
    jwtSigningKey: mall
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt
  aliyun:
    key:
      accessKeyId: yourAliyunAccessKey
      accessKeySecret: yourAliyunKeySecret
    rocketMq:
      enable: true
      reliableMessageConsumer: true
      reliableMessageProducer: false
      namesrvAddr: mall-mq-rocket:9876
      instanceName: mall-provider-opc
      consumerGroup: CID_OPC
      producerGroup: PID_OPC
    sms:
      signName: 快乐学习网
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: Dysmsapi
      domain: dysmsapi.aliyuncs.com
